version: 2.1

orbs:
  go: circleci/go@1.7.0
  sonarqube: sonarsource/sonarqube@1.1.0

workflows:
  version: 2
  go-build-test-and-dockerize:
    jobs:
      - build
      - test
      - docker
      - static test

jobs:
  build:
    docker:
      - image: cimg/go:1.21.0
    steps:
      - checkout
      - run: echo 'Build Stage Started'
      - run: mkdir -p .build
      - run: go mod init basic_go/v2
      - run: go mod tidy
      - run: go build -o iugo_app main.go
      - run: cp go.mod .build/go.mod.orig
      - run: echo 'Build Stage Ended'
      - persist_to_workspace:
          root: .
          paths:
            - iugo_app

  test:
    docker:
      - image: cimg/go:1.21.0
    steps:
      - checkout
      - run: echo 'Test Stage Started'
      - run: go mod init basic_go/v2
      - run: go test
      - run: echo 'Test Stage Ended'

  docker:
    docker:
      - image: cimg/go:1.21.0
    steps:
      - checkout
      - attach_workspace:
          at: /workspace
      - setup_remote_docker
      - run: echo 'Dockerization Stage Started'
      - run: |
          docker build -t iugo_app:v1 .
      - run: echo 'Dockerization Stage Ended'

  static test:
    docker:
      - image: cimg/go:1.21.0
    steps:
      - checkout
      - sonarqube/scan:
          server_url: "http://localhost:9000"
          login: ""