name: Go CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: go ci
        run: echo "A line"
        shell: bash

  test:
    runs-on: ubuntu-latest
    steps:
      - name: go test ci
        run: echo "Next words"
        shell: bash