name: Go CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ "ubuntu-latest" ]
        go-version: [ "1.21" ]
    runs-on:  ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: go ci
        run: |
          echo 'Build Stage Started'
          sh 'mkdir -p .build'
          sh 'go build main.go'
          sh 'cp go.mod .build/go.mod.orig'
          echo 'Build Stage Ended'
        shell: bash

  test:
    strategy:
      matrix:
        os: [ "ubuntu-latest" ]
        go-version: [ "1.21" ]
    runs-on:  ${{ matrix.os }}
    steps:
      - name: go test ci
        run: |
          echo 'Test Stage Started'
          sh 'go test'
          echo 'Test Stage Ended'
        shell: bash